accounts/urls.py
from django.urls import path
from . import views
app_name='accounts'
urlpatterns = [
  path('signup',views.signup_view,name='signup'),
	path('login',views.login_view,name='login'),
path('logout',views.logout_view,name='logout'),

]

articles/urls.py
from django.urls import path
from . import views
app_name='articles'
urlpatterns = [

    path('', views.articles_list,name='list'),
    path('create',views.create_article,name='create'),
    path('<slug>', views.articles_detail,name='detail'),


]

firstproject/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
app_name='firstproject'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.aboutpage,name='about'),
    path('', views.homepage,name='home'),
    path('articles/',include('articles.urls')),
    path('accounts/',include('accounts.urls'))
]
urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User
class Articles(models.Model):
	title=models.CharField(max_length=100)
	slug=models.SlugField()
	body=models.TextField()
	date=models.DateTimeField(auto_now_add=True)
	image=models.ImageField(default='default.jpg',blank=True)
	author=models.ForeignKey(User,default=None,on_delete=models.CASCADE)
	def __str__(self):
	    return self.title

	def snip(self):
	    return self.body[:50]+" ..."

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout
def signup_view (request):
    if request.method=='POST':
        form=UserCreationForm(request.POST)
        if form.is_valid():
            user=form.save()
            login(request, user)
            return redirect('articles:list')
    else:

        form=UserCreationForm()
        # args={'form':form}
    return render(request,'accounts/signup.html',{'form':form})

def login_view (request):
    if request.method=='POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user=form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:

        form=AuthenticationForm()
        # args={'form':form}
    return render(request,'accounts/login.html',{'form':form})

def logout_view (request):
    # if request.method=='POST':
    logout(request)
    return redirect('articles:list')

articles/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from . import models
from . import create_form
def articles_list (request):
    articles=models.Articles.objects.all().order_by('date')
    args={'articles':articles}
    return render(request,'articles/articleslist.html',args)

def articles_detail (request,slug):

    # return HttpResponse(slug)
    article=models.Articles.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article':article})
@login_required(login_url="/accounts/login")
def create_article (request):
    if request.method=='POST':
        form=create_form.CreateArticle(request.POST,request.FILES)
        if form.is_valid:
            instance=form.save(commit=False)
            instance.author=request.user
            instance.save()
            return redirect('articles:list')
    else:
        form=create_form.CreateArticle()
    return render(request, 'articles/create_article.html',{'form':form})

firstproject/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
def aboutpage (request):
		#return HttpResponse('hi!im sina')
		return render(request,'about.html')


def homepage(request):
	 #return HttpResponse('wellcome!!')
	 return render(request,'home.html')

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block body %}
<h1> login </h1>
<form class="signup" action="{% url 'accounts:login' %}" method="post">
{{form}}
{%csrf_token%}
{%if request.GET.next%}
<input type="hidden" name="next" value="{{request.GET.next}}">
{%endif%}

    <input type="submit" value="login" name="">
</form>

{%endblock%}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block body %}
<h1>sign up</h1>
<form class="signup" action="/accounts/signup" method="post">
{{form}}
{%csrf_token%}

    <input type="submit" value="signup" name="">
</form>

{%endblock%}

articles/templates/articles/article_detail.html
{% extends 'base.html' %}
 {% block title %}
    {{article.title}}
 {% endblock %}
 {% block body %}

    <div class="article-detail">
         <div class="article">

      <img src="{{article.image.url}}" alt="">
      <h2>{{article.title}}</h2>
      <hr>
      <p class="article-body">{{article.body}}</p>
      <p class="article-date">{{article.date}}</p>
         </div>
    </div>

 {% endblock %}

articles/templates/articles/articleslist.html
{% extends 'base.html' %}
 {% block title %}
    Articles
 {% endblock %}
 {% block body %}

      <h1>articles list</h1>
<div class="articles">
      {% for  article in articles %}
    <div class="article">
      <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>
      <!--<p>{{article.body}}</p>--> <!-- for full article text-->
      <p>{{article.snip}}</p> <!--for 50 caracter view-->
      <p>{{article.date}}</p>
      <p class="author">added by {{article.author.username}}</p>
    </div>
      {% endfor %}
</div>
 {% endblock %}

articles/templates/articles/create_article.html
{% extends 'base.html' %}
<!-- {% block title %}-->
<!--    Articles_detail-->
<!-- {% endblock %}-->
 {% block body %}
<div class="create_articles" >
      <h1>create articles</h1>
    <form class="site-form" action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
        {{form}}
        {% csrf_token %}
<input type="submit" name="" value="create">
</form>


</div>
 {% endblock %}

templates/about.html
{% extends 'base.html' %}
 {% block title %}
   about
 {% endblock %}
 {% block body %}
<div class="about">
    <p>
        Hello every body!i'm sina majidi a computer buff!
    </p>
    <p>
        i'm interested in Robotics,embeded systems,artifical inteligense,programming and technology and
        im trying to make a place to share our articles.
    </p>
    
</div>
 {% endblock %}

templates/base.html
{% load static %}
<html>
  <head>
    <title>
      {% block title %}
      {% endblock %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">

  </head>
  <header>
      <nav>
    <ul>
         <li>
        <a class="highlight" href="/"> HOME </a>
      </li>
        <li>
        <a class="highlight" href="/about"> about </a>
      </li>
        <li>
        <a class="highlight" href="{% url 'articles:list' %}"> see the articles </a>
      </li>
      {% if user.is_authenticated %}
      <li>
<!--        <form class="logout0" action="{% url 'accounts:logout'%}" method="post">-->
<!--         {%csrf_token%}-->
<!--          <button type="submit" value="logout">logout</button>-->
<!--        </form>-->
        <a class="logout" href="{% url 'accounts:logout' %}"> logout </a>
      </li>
       <li>
        <a class="highlight" href="{% url 'articles:create' %}"> creat new article </a>
      </li>
      {% else %}
      <li>
        <a class="highlight" href ="{% url 'accounts:login' %}"> login </a>
      </li>
       <li>
        <a class="highlight" href="{% url 'accounts:signup' %}"> signup </a>
      </li>
      {% endif %}
    </ul>

  </nav>
  </header>
  <body>
  <div class="wrapper">
     {% block body %}
      {% endblock %}
  </div>
  </body>

</html>

templates/home.html
{% extends 'base.html' %}
 {% block title %}
   home
 {% endblock %}
 {% block body %}
<div class="wrapper">
    <div class="welcome">
        <p>welcome to my weblog!</p>
        <p>i hope we can share our articles about IOT,Programing,Computer sciense,Artifical inteligense and etc...</p>
         <p>you can signup and help world using your knowledge!</p>
    </div>

</div>
 {% endblock %}